name: CI-workflow

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  # build on ubuntu
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Build
      run: dotnet build
    
    - name: Test
      run: dotnet test --no-build --verbosity normal
      
      
  dotnet-format:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: .Net 6
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "6.0.x"
          include-prerelease: true
      
      - name: Install dotnet-format tool
        run: dotnet tool install -g dotnet-format

      - name: Check out code
        uses: actions/checkout@v2

      - name: Run dotnet format
        run: dotnet format --verify-no-changes
